// <auto-generated />
namespace StudyForum.Db.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FileContentLengthadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FileContentLengthadded));
        
        string IMigrationMetadata.Id
        {
            get { return "201804011117375_File ContentLength added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
